#! /bin/sh

gap=10
PANEL_HEIGHT=15

bspc monitor DP-1 -d one
bspc monitor DP-5 -d two

bspc config window_gap $gap
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

bspc config gapless_monocle      false
bspc config borderless_monocle   true

bspc config border_width         5

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.66

bspc config normal_border_color '#969896'
bspc config active_border_color '#c5c8c6'
bspc config focused_border_color '#de935f'
bspc config presel_feedback_color '#8abeb7'

sh ~/.config/bspwm/scripts/wallpaper.sh &
xautolock -corners --00 -time 20 -locker 'sh ~/.config/bspwm/scripts/lockscreen.sh' &
sxhkd &

sh ~/.config/bspwm/autostart &

polybar main &
polybar default &
xdo above -t $(xdo id -n root) $(xdo id -n polybar) &
